path:
  ckpt_path: "./output/ckpt/LJSpeech"
  log_path: "./output/log/LJSpeech"
  result_path: "./output/result/LJSpeech"
optimizer:
  batch_size: 32
  betas: [0.9, 0.999]
  eps: 0.0000001
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  init_lr: 0.000125
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 50000
alignment:
  reduction_factors: [5, 4, 3, 2]
  reduce_interval: [0, 200, 400, 600]
length:
  length_weight: 1.
kl:
  kl_weight: 1.
  kl_weight_init: 0.00000001
  kl_weight_increase_epoch: 1000
  kl_weight_end: 0.00001
